<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
  </PropertyGroup>

  <!-- Explicitly allow test project to access things with 'internal' access modifier -->
  <ItemGroup>
    <InternalsVisibleTo Include="FoolproofSampleSystem.Tests" />
  </ItemGroup>

  <!-- Only generates the XML doc when in debug mode -->
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- Packages to include regardless of mode -->
  <ItemGroup>
    <!-- Use the latest version of XML cryptography to override the unsafe transitive dependency in NPOI -->
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.*" />
    <PackageReference Include="NPOI" Version="2.8.*" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.*" />
  </ItemGroup>

  <!-- Only use StyleCop when in debug mode -->
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <!-- Setting private assets ensures this dependency is ignored in production -->
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <AdditionalFiles Include="../stylecop.json" />
  </ItemGroup>

  <!-- Internal projects to reference -->
  <ItemGroup>
    <ProjectReference Include="..\InterProcessIO\InterProcessIO.csproj" />
  </ItemGroup>

</Project>
